/*
 * Criado por Pedro Ramos Krauze Diehl
 * last update 26/10/2016 - 14:51
 * TODO:
 * - Formatação das caixas monetarias
 */
package caixa;

public class gui extends javax.swing.JFrame {
	
	public static String linha;

	public gui() {
		initComponents();
	} 

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
	 * code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        totalvendas = new javax.swing.JTextField();
        caixadiaanterior = new javax.swing.JTextField();
        caixaatual = new javax.swing.JTextField();
        totaldinheiro = new javax.swing.JTextField();
        totalcartao = new javax.swing.JTextField();
        acrescimo = new javax.swing.JTextField();
        retirada = new javax.swing.JTextField();
        try {
            jTextField1 =(javax.swing.JTextField)java.beans.Beans.instantiate(getClass().getClassLoader(), "caixa.GUI_jTextField1");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        re1 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        calcula = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        ped = new javax.swing.JTextField();
        re2 = new javax.swing.JTextField();
        re3 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        caixa = new javax.swing.JTextField();
        enviardados = new javax.swing.JButton();
        re4 = new javax.swing.JTextField();
        retirada1 = new javax.swing.JTextField();
        retirada2 = new javax.swing.JTextField();
        retirada3 = new javax.swing.JTextField();
        load = new javax.swing.JButton();

        jTextField7.setText("Comente aqui");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        totalvendas.setText("0");
        totalvendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalvendasMouseClicked(evt);
            }
        });
        totalvendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalvendasActionPerformed(evt);
            }
        });
        totalvendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalvendasKeyPressed(evt);
            }
        });

        caixadiaanterior.setText("0");
        caixadiaanterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caixadiaanteriorMouseClicked(evt);
            }
        });
        caixadiaanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixadiaanteriorActionPerformed(evt);
            }
        });

        caixaatual.setText("0");
        caixaatual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caixaatualMouseClicked(evt);
            }
        });
        caixaatual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaatualActionPerformed(evt);
            }
        });

        totaldinheiro.setText("0");
        totaldinheiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totaldinheiroMouseClicked(evt);
            }
        });
        totaldinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaldinheiroActionPerformed(evt);
            }
        });

        totalcartao.setText("0");
        totalcartao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalcartaoMouseClicked(evt);
            }
        });
        totalcartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalcartaoActionPerformed(evt);
            }
        });

        acrescimo.setText("0");
        acrescimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acrescimoMouseClicked(evt);
            }
        });
        acrescimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acrescimoActionPerformed(evt);
            }
        });

        retirada.setText("0");
        retirada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retiradaMouseClicked(evt);
            }
        });
        retirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiradaActionPerformed(evt);
            }
        });

        jTextField2.setText("Caixa dia Anterior");
        jTextField2.setFocusable(false);

        jTextField3.setText("Caixa Atual");
        jTextField3.setFocusable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setText("Total Dinheiro");
        jTextField4.setFocusable(false);

        jTextField5.setText("Total Cartão");
        jTextField5.setFocusable(false);

        re1.setText("Retirada 1");
        re1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                re1MouseClicked(evt);
            }
        });
        re1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re1ActionPerformed(evt);
            }
        });

        jTextField9.setText("Acrescimo");
        jTextField9.setFocusable(false);

        calcula.setText("Calcular");
        calcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaActionPerformed(evt);
            }
        });

        jTextField6.setText("PDV");
        jTextField6.setFocusable(false);

        ped.setText("0");
        ped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedMouseClicked(evt);
            }
        });
        ped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedActionPerformed(evt);
            }
        });

        re2.setText("Retirada 2");
        re2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                re2MouseClicked(evt);
            }
        });

        re3.setText("Retirada 3");
        re3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                re3MouseClicked(evt);
            }
        });

        jTextField10.setText("Caixa R$ = ");
        jTextField10.setFocusable(false);

        caixa.setText("0");
        caixa.setFocusable(false);
        caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaActionPerformed(evt);
            }
        });

        enviardados.setText("Enviar Dados");
        enviardados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviardadosActionPerformed(evt);
            }
        });

        re4.setText("Retirada 4");
        re4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                re4MouseClicked(evt);
            }
        });
        re4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re4ActionPerformed(evt);
            }
        });

        retirada1.setText("0");
        retirada1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retirada1MouseClicked(evt);
            }
        });

        retirada2.setText("0");
        retirada2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retirada2MouseClicked(evt);
            }
        });

        retirada3.setText("0");
        retirada3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retirada3MouseClicked(evt);
            }
        });
        retirada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirada3ActionPerformed(evt);
            }
        });

        load.setText("Carregar Caixa dia Anterioir");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enviardados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caixa, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(re3)
                            .addComponent(re2)
                            .addComponent(jTextField6)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField5)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(re1)
                            .addComponent(jTextField9)
                            .addComponent(re4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retirada2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(retirada1)
                            .addComponent(acrescimo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalcartao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totaldinheiro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(caixaatual, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalvendas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(retirada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ped)
                            .addComponent(retirada3)
                            .addComponent(caixadiaanterior))))
                .addContainerGap())
            .addComponent(calcula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalvendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixadiaanterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(caixaatual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaldinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalcartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(re1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retirada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retirada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retirada3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(load, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcula, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviardados))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixaatualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaatualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaatualActionPerformed

    private void acrescimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acrescimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acrescimoActionPerformed

    private void retiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retiradaActionPerformed

    private void calculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculaActionPerformed
	
		function.sum();
    }//GEN-LAST:event_calculaActionPerformed

    private void caixadiaanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadiaanteriorActionPerformed
		
    }//GEN-LAST:event_caixadiaanteriorActionPerformed

    private void totaldinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaldinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaldinheiroActionPerformed

    private void totalcartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalcartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalcartaoActionPerformed

    private void caixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaActionPerformed
        
    }//GEN-LAST:event_caixaActionPerformed

    private void pedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pedActionPerformed

    private void enviardadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviardadosActionPerformed
			
			//SALVA O CAIXA ATUAL NO ARQUVIO CAIXA.TXT
			function.saveDb();
			
			function.sendMail();
    }//GEN-LAST:event_enviardadosActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void re1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re1ActionPerformed

    private void caixadiaanteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caixadiaanteriorMouseClicked
        caixadiaanterior.setText("");
    }//GEN-LAST:event_caixadiaanteriorMouseClicked

    private void caixaatualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caixaatualMouseClicked
       caixaatual.setText("");
    }//GEN-LAST:event_caixaatualMouseClicked

    private void totaldinheiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totaldinheiroMouseClicked
        totaldinheiro.setText("");
    }//GEN-LAST:event_totaldinheiroMouseClicked

    private void totalcartaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalcartaoMouseClicked
        totalcartao.setText("");
    }//GEN-LAST:event_totalcartaoMouseClicked

    private void acrescimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acrescimoMouseClicked
       acrescimo.setText("");
    }//GEN-LAST:event_acrescimoMouseClicked

    private void retiradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retiradaMouseClicked
        retirada.setText("");
    }//GEN-LAST:event_retiradaMouseClicked

    private void retirada1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retirada1MouseClicked
        retirada1.setText("");
    }//GEN-LAST:event_retirada1MouseClicked

    private void retirada2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retirada2MouseClicked
        retirada2.setText("");
    }//GEN-LAST:event_retirada2MouseClicked

    private void retirada3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retirada3MouseClicked
        retirada3.setText("");
    }//GEN-LAST:event_retirada3MouseClicked

    private void pedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedMouseClicked
        ped.setText("");
    }//GEN-LAST:event_pedMouseClicked

    private void re1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_re1MouseClicked
        re1.setText("");
    }//GEN-LAST:event_re1MouseClicked

    private void re2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_re2MouseClicked
         re2.setText("");
    }//GEN-LAST:event_re2MouseClicked

    private void re3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_re3MouseClicked
         re3.setText("");
    }//GEN-LAST:event_re3MouseClicked

    private void re4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_re4MouseClicked
         re4.setText("");
    }//GEN-LAST:event_re4MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        caixadiaanterior.setText(linha);
    }//GEN-LAST:event_loadActionPerformed

    private void totalvendasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalvendasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalvendasKeyPressed

    private void totalvendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalvendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalvendasActionPerformed

    private void totalvendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalvendasMouseClicked
        totalvendas.setText("");
    }//GEN-LAST:event_totalvendasMouseClicked

    private void re4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re4ActionPerformed

    private void retirada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirada3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retirada3ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		//FAZ A LEITURA DO ARQUIVO caixa.txt
		
		function.readDb();
		
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new gui().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField acrescimo;
    public static javax.swing.JTextField caixa;
    public static javax.swing.JTextField caixaatual;
    public static javax.swing.JTextField caixadiaanterior;
    private javax.swing.JButton calcula;
    private javax.swing.JButton enviardados;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton load;
    public static javax.swing.JTextField ped;
    public static javax.swing.JTextField re1;
    public static javax.swing.JTextField re2;
    public static javax.swing.JTextField re3;
    public static javax.swing.JTextField re4;
    public static javax.swing.JTextField retirada;
    public static javax.swing.JTextField retirada1;
    public static javax.swing.JTextField retirada2;
    public static javax.swing.JTextField retirada3;
    public static javax.swing.JTextField totalcartao;
    public static javax.swing.JTextField totaldinheiro;
    public static javax.swing.JTextField totalvendas;
    // End of variables declaration//GEN-END:variables
}
